services:
  palworld:
    restart: unless-stopped
    container_name: palworld-proton-server
    image: palworld-proton
    env_file:
      - ./default.env
    volumes:
      - ./server:/app
      - /etc/localtime:/etc/localtime:ro
      - /etc/machine-id:/etc/machine-id:ro
    logging:
      driver: "local"
      options:
        max-size: "10m"
        max-file: "3"
    ports:
      - target: 8211
        published: 8211
        protocol: udp
        mode: host
      - target: 8212
        published: 8212
        protocol: tcp
        mode: host
      - target: 25575
        published: 25575
        protocol: tcp
        mode: host
      - target: 27015
        published: 27015
        protocol: tcp
    networks:
      - palworld

networks:
  palworld:
    driver: bridge
